export const bankList = [
    'Kuda Microfinance',
    'Moniepoint',
    'Opay',
    'PalmPay',
    'ACCESS BANK',
    'Citibank Nigeria',
    'Diamond Bank',
    'Ecobank',
    'Fidelity Bank',
    'First Bank',
    'First City Monument Bank (FCMB)',
    'Guaranty Trust Bank (GTB)',
    'Heritage Bank',
    'Keystone Bank',
    'Polaris Bank',
    'Providus Bank',
    'Stanbic IBTC Bank',
    'Standard Chartered Bank',
    'Sterling Bank',
    'Suntrust Bank',
    'Union Bank',
    'United Bank for Africa (UBA)',
    'Unity Bank',
    'Wema Bank',
    'Zenith Bank',
    'VFD Bank',
  ];
  